version: 2.1
on:
  pull_request:
    branches:
      - main

# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@4.9
  cypress: cypress-io/cypress@3

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  jest_and_cypress: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - node/test:
          name: Jest Tests
          # https://circleci.com/developer/images/image/cimg/node
          version: "18.17"
          pkg-manager: npm
      - cypress/run:
          name: Cypress Tests
          start-command: npm run dev
