name: Main Push
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Deploy on Push to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCREENCOMPARE }}"
          channelId: live
          projectId: screencompare
